### ISSUE TITLE
Finetuning with labels

### ISSUE THREAD

**Issue by gillesmeyhi** [jimbozhang/hf_transformers_custom_model_ced#6]
Hi,
In the ESC-50 finetuning notebook, the output_dim is set to 50.
But there is no reference to the esc-50 labels, so during inference just the 50 first labels of AS are used? How do we get the ESC-50 labels?

**Comment by jimbozhang** [comment]
> Hi, In the ESC-50 finetuning notebook, the output_dim is set to 50. But there is no reference to the esc-50 labels, so during inference just the 50 first labels of AS are used? How do we get the ESC-50 labels?

The labels are loaded from "ESC-50-master/meta/esc50.csv" in the code block 3 of the notebook.
